name: purple
description: MVP playful, on-device style assistant (Whisper -> Liquid -> Liquid -> TTS). Actions disabled; response only.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  flutter_tts: ^3.8.3
  uuid: ^4.4.0
  path_provider: ^2.1.3
  speech_to_text: ^6.6.1
  device_info_plus: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  http: ^1.2.2
  flutter_lints: ^3.0.1
  rename: ^3.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/avatars/purple.png
    - assets/avatars/red.png
    - assets/avatars/green.png
